function [sol_cells_saved, residuals] = solve_pfm(fd, params, dof)
%SOLVE_PFM Advance the phase-field model without concentration coupling.
%   [sol_cells_saved, residuals] = solve_pfm(fd, params, dof) initializes
%   the nurse cells, oocyte, and cluster phase fields and advances them in
%   time until the requested final time or an early residual tolerance is
%   reached.
%
%   Inputs:
%     fd     Finite-difference operators and geometry data.
%     params Model parameters for the uncoupled phase-field system.
%     dof    Discretization sizes and output cadence.
%
%   Outputs:
%     sol_cells_saved Saved phase fields at the requested save times.
%     residuals       Relative residual at each saved time.
%
% By Naghmeh Akhavan March 2025

% Common indices used throughout the update.
nurse_idx = 1:dof.n_cells_nurse;
oocyte_idx = dof.n_cells - 1;
cluster_idx = dof.n_cells;
save_interval = dof.n_time / dof.n_saved;

% Initialize the phase fields on the spatial grid.
sol_cells = zeros(dof.n_space, dof.n_space, dof.n_cells);
for i = 1:dof.n_cells
    sol_cells(:, :, i) = initialize_u( ...
        fd.x_mesh, fd.y_mesh, params.x_centers(i), params.y_centers(i), params.cell_radi(i));
end

% Vectorize the state for the time-marching loop.
sol_cells = reshape(sol_cells, [dof.n_space^2, dof.n_cells]);

% Preallocate saved outputs.
sol_cells_saved = zeros(dof.n_space, dof.n_space, dof.n_cells, dof.n_saved);
residuals = zeros(1, dof.n_saved);
save_count = 0;

for i = 1:dof.n_time
    sol_cells_old = sol_cells;

    % Smoothed indicator h(u) = 3u^2 - 2u^3 and the aggregate nurse phase.
    h_sol_cells = 3 * sol_cells.^2 - 2 * sol_cells.^3;
    phi_sum = sum(h_sol_cells(:, nurse_idx), 2);
    vol_cells = params.h_space^2 * sum(h_sol_cells, 1);

    % Update nurse cells.
    for m = nurse_idx
        sol_cells(:, m) = sol_cells(:, m) + params.h_time * ( ...
            params.dval(1) * fd.laplacian * sol_cells(:, m) ...
            + sol_cells(:, m) .* (1 - sol_cells(:, m)) .* ( ...
                sol_cells(:, m) - 0.5 + (params.target_volumes(m) - vol_cells(m)) ...
                - params.beta(1, 1) * (phi_sum - h_sol_cells(:, m)) ...
                - params.beta(1, 2) * h_sol_cells(:, oocyte_idx) ...
                - params.beta(1, 3) * h_sol_cells(:, cluster_idx) ...
                - params.beta_s * fd.h_epithelial ...
                + fd.laplacian * ( ...
                    params.eta_s * fd.h_epithelial ...
                    + params.eta(1, 1) * (phi_sum - h_sol_cells(:, m)) ...
                    + params.eta(1, 2) * h_sol_cells(:, oocyte_idx) ...
                    + params.eta(1, 3) * h_sol_cells(:, cluster_idx) ...
                    + params.gamma * h_sol_cells(:, m))));
    end

    % Update the oocyte.
    sol_cells(:, oocyte_idx) = sol_cells(:, oocyte_idx) + params.h_time * ( ...
        params.dval(2) * fd.laplacian * sol_cells(:, oocyte_idx) ...
        + sol_cells(:, oocyte_idx) .* (1 - sol_cells(:, oocyte_idx)) .* ( ...
            sol_cells(:, oocyte_idx) - 0.5 + (params.target_volumes(oocyte_idx) - vol_cells(oocyte_idx)) ...
            - params.beta(2, 1) * phi_sum ...
            - params.beta(2, 3) * h_sol_cells(:, cluster_idx) ...
            - params.beta_s * fd.h_epithelial ...
            + fd.laplacian * ( ...
                params.eta_s * fd.h_epithelial ...
                + params.eta(2, 1) * phi_sum ...
                + params.eta(2, 3) * h_sol_cells(:, cluster_idx) ...
                + params.gamma * h_sol_cells(:, oocyte_idx))));

    % Update the cluster.
    sol_cells(:, cluster_idx) = sol_cells(:, cluster_idx) + params.h_time * ( ...
        params.dval(3) * fd.laplacian * sol_cells(:, cluster_idx) ...
        + sol_cells(:, cluster_idx) .* (1 - sol_cells(:, cluster_idx)) .* ( ...
            sol_cells(:, cluster_idx) - 0.5 + params.alpha * (params.target_volumes(cluster_idx) - vol_cells(cluster_idx)) ...
            - params.beta(3, 1) * phi_sum ...
            - params.beta(3, 2) * h_sol_cells(:, oocyte_idx) ...
            - params.beta_s * fd.h_epithelial ...
            + fd.laplacian * ( ...
                params.eta_s * fd.h_epithelial ...
                + params.eta(3, 1) * phi_sum ...
                + params.eta(3, 2) * h_sol_cells(:, oocyte_idx) ...
                + params.gamma * h_sol_cells(:, cluster_idx))));

    res = norm(sol_cells - sol_cells_old) / norm(sol_cells_old);

    if mod(i, save_interval) == 0
        save_count = save_count + 1;
        sol_cells_saved(:, :, :, save_count) = reshape(sol_cells, dof.n_space, dof.n_space, dof.n_cells);
        residuals(save_count) = res;

        fprintf('Saved time step %d of %d. Relative residual: %.3e.\n', i, dof.n_time, res);

        if res < params.tol
            break
        end
    end
end

residuals = residuals(1:save_count);
